# Generated by Django 4.1.7 on 2023-10-04 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cardata', '0003_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
