# Generated by Django 4.1.7 on 2023-10-04 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cardata', '0004_delete_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
    ]
